---
galaxy_info:
  author: companyx infra team
  description: Deploy nginx container for companyx application
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Amazon
      versions:
        - all
  galaxy_tags:
    - nginx
    - podman
    - container

collections:
  - ansible.posix
  - containers.podman

dependencies: []
